### PR TITLE
bz - integrated jobs service into codebase

### LINKED ISSUE #8: Add jobs code from Bryan T into HappyCows
https://github.com/brownfield-team/kanban-populator/pull/24

### PR DESCRIPTION
**Pull request by bzamora020**
# What was done:

- In this PR, we integrated a service that allows running background jobs and tracking their progress in a database table. 
- Integrated into happy cows codebase

Followed Bryan T's [example](https://github.com/brownfield-team/kanban-populator/pull/24)

### CODE REVIEW

**Review by kheff16 — COMMENTED** [review]
Looks good! Did you run eslint?

**Review by sethvanb — APPROVED** [review]
LGTM

**Review by andrewhlu — DISMISSED** [review]
The code changes look good to me, I'm not sure how to test this though. Hoping @btk5h or @sethvanb can provide more insight on this.

**Review by sethvanb — COMMENTED** [review]
Add controller to test job service

**Review by pconrad — DISMISSED** [review]
Bryan Z:

This looks great!  But there's a few things I think we need beyond Bryan T's code that I'm going to add before we merge this:

* A simple Jobs controller to let us see the jobs records.
* A sample job so that we can test the system, and use that as an example for making other jobs.

**Review by sethvanb — APPROVED** [review]
LGTM

**Review by sethvanb — APPROVED** [review]
Tested on Heroku and LGTM

**Pull request merged**
